"""
build_suburbs.py — GetReal suburb page generator
=================================================
Generates static HTML pages for NSW and VIC suburbs.

NSW: fetches suburb + property_type + sale_price from Supabase property_sales.
     Computes real medians, percentiles, and price distributions.
     Caches raw data to _nsw_suburb_cache.json (reuse with --no-fetch).

VIC: reads suburb-data.json (generated by load_vic_quarterly.py).
     Shows median + annual sales. Budget access estimated via log-normal.

Output:
  suburbs/nsw/{slug}.html     — one per NSW suburb (10+ total sales)
  suburbs/vic/{slug}.html     — one per VIC suburb (10+ annual sales)
  suburbs/nsw/index.html      — NSW suburb listing
  suburbs/vic/index.html      — VIC suburb listing
  suburbs/index.html          — combined index
  sitemap-suburbs.xml         — suburb sitemap (linked from sitemap.xml)

Usage:
  export SUPABASE_SECRET=your_secret_key_here
  python3 build_suburbs.py

Options:
  --no-fetch   Skip Supabase fetch, use _nsw_suburb_cache.json
  --state      Only build 'nsw' or 'vic'
  --min-sales  Minimum total sales (default: 10)
  --limit      Only build first N pages per state (for testing)
  --dry-run    Compute stats and report counts without writing HTML
"""

import argparse
import json
import math
import os
import re
import sys
import time
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path

import requests

# ── Config ──────────────────────────────────────────────────────────────────────

SUPABASE_URL    = "https://lkxzxeeeqfiymunpqvgt.supabase.co"
SUPABASE_SECRET = os.environ.get("SUPABASE_SECRET", "")

NSW_CACHE   = "_nsw_suburb_cache.json"
VIC_JSON    = "suburb-data.json"
OUT_DIR     = Path("suburbs")
BASE_URL    = "https://get-real.co"
TODAY       = date.today().isoformat()
MIN_SALES   = 20

# Budget rows shown in the access table (relative to suburb median, rounded to $25k)
BUDGET_RATIOS = [0.65, 0.82, 1.0, 1.35]

# Price brackets for distribution chart (dynamic per suburb — see compute_brackets)
# Grade thresholds
GRADES = [
    (60, "A", "Strong access",  "#2e7d32", "#e8f5e9"),
    (40, "B", "Competitive",    "#1565c0", "#e3f2fd"),
    (20, "C", "Limited",        "#e65100", "#fff3e0"),
    (0,  "D", "Very limited",   "#c62828", "#ffebee"),
]

GREEN = "#4caf50"   # suburb page accent

# ── Helpers ─────────────────────────────────────────────────────────────────────

def slugify(name):
    return re.sub(r'[^a-z0-9]+', '-', (name or "").lower()).strip('-')


def title_case(s):
    return " ".join(w.capitalize() for w in (s or "").split())


def fmt_price(p):
    if p >= 1_000_000:
        v = p / 1_000_000
        s = f"{v:.2f}".rstrip('0').rstrip('.')
        return f"${s}M"
    if p >= 1_000:
        v = p / 1_000
        s = f"{v:.0f}"
        return f"${s}k"
    return f"${int(p)}"


def fmt_price_full(p):
    return f"${p:,.0f}"


def percentile(sorted_prices, pct):
    if not sorted_prices:
        return 0
    n = len(sorted_prices)
    idx = (n - 1) * pct / 100
    lo = int(idx)
    hi = min(lo + 1, n - 1)
    return int(sorted_prices[lo] * (1 - idx + lo) + sorted_prices[hi] * (idx - lo))


def budget_access(sorted_prices, budget):
    """Percentage of sales at or below budget (NSW — real data)."""
    if not sorted_prices:
        return 0
    count = sum(1 for p in sorted_prices if p <= budget)
    return round(100 * count / len(sorted_prices))


def vic_budget_access(median, budget):
    """Log-normal approximation for VIC (no individual records available)."""
    if median <= 0 or budget <= 0:
        return 0
    sigma = 0.4
    z = (math.log(budget) - math.log(median)) / sigma
    return max(0, min(100, round(50 * (1 + math.erf(z / math.sqrt(2))))))


def get_grade(pct):
    for threshold, letter, label, color, bg in GRADES:
        if pct >= threshold:
            return letter, label, color, bg
    return "D", "Very limited", "#c62828", "#ffebee"


def compute_brackets(median):
    """5 dynamic price brackets centred around median."""
    def snap(v):
        if v < 300_000:   return round(v / 25_000)  * 25_000
        if v < 1_000_000: return round(v / 50_000)  * 50_000
        if v < 3_000_000: return round(v / 100_000) * 100_000
        return round(v / 250_000) * 250_000

    b = [snap(median * r) for r in (0.5, 0.8, 1.2, 1.8)]
    return [
        (0,    b[0], f"Under {fmt_price(b[0])}"),
        (b[0], b[1], f"{fmt_price(b[0])}–{fmt_price(b[1])}"),
        (b[1], b[2], f"{fmt_price(b[1])}–{fmt_price(b[2])}"),
        (b[2], b[3], f"{fmt_price(b[2])}–{fmt_price(b[3])}"),
        (b[3], float('inf'), f"Over {fmt_price(b[3])}"),
    ]


def round_budget(v):
    return max(250_000, round(v / 25_000) * 25_000)


# ── Supabase fetch ───────────────────────────────────────────────────────────────

def sb_headers():
    return {
        "apikey":        SUPABASE_SECRET,
        "Authorization": f"Bearer {SUPABASE_SECRET}",
    }


def fetch_nsw_sales():
    """Fetch suburb + property_type + sale_price for all NSW rows."""
    records = []
    page    = 1000
    offset  = 0
    print("Fetching NSW property_sales from Supabase...")
    while True:
        url = (f"{SUPABASE_URL}/rest/v1/property_sales"
               f"?select=suburb,property_type,sale_price"
               f"&state=eq.NSW&limit={page}&offset={offset}")
        r = requests.get(url, headers=sb_headers(), timeout=30)
        if r.status_code != 200:
            print(f"  ERROR {r.status_code}: {r.text[:200]}")
            break
        batch = r.json()
        if not batch:
            break
        records.extend(batch)
        offset += len(batch)
        if offset % 50_000 == 0:
            print(f"  {offset:,} rows fetched...")
        if len(batch) < page:
            break
        time.sleep(0.1)
    print(f"  Total: {len(records):,} NSW records")
    return records


def load_or_fetch_nsw(no_fetch=False):
    if no_fetch and os.path.exists(NSW_CACHE):
        print(f"Loading NSW data from {NSW_CACHE}...")
        with open(NSW_CACHE) as f:
            return json.load(f)
    if not SUPABASE_SECRET:
        if os.path.exists(NSW_CACHE):
            print(f"No SUPABASE_SECRET — using {NSW_CACHE}")
            with open(NSW_CACHE) as f:
                return json.load(f)
        print("ERROR: SUPABASE_SECRET not set and no cache file found.")
        sys.exit(1)
    records = fetch_nsw_sales()
    with open(NSW_CACHE, "w") as f:
        json.dump(records, f)
    print(f"  Cached to {NSW_CACHE}")
    return records


# ── NSW stats ────────────────────────────────────────────────────────────────────

def compute_nsw_stats(records, min_sales=10):
    """Aggregate raw sale records into per-suburb stats."""
    by = defaultdict(lambda: defaultdict(list))
    for r in records:
        suburb = (r.get("suburb") or "").strip().lower()
        ptype  = (r.get("property_type") or "").strip().lower()
        price  = r.get("sale_price") or 0
        if suburb and ptype and price > 50_000:
            by[suburb][ptype].append(price)

    stats = {}
    for suburb, types in by.items():
        total = sum(len(v) for v in types.values())
        if total < min_sales:
            continue
        type_stats = {}
        for ptype, prices in types.items():
            if len(prices) < 3:
                continue
            sp = sorted(prices)
            type_stats[ptype] = {
                "count":  len(sp),
                "median": percentile(sp, 50),
                "p10":    percentile(sp, 10),
                "p25":    percentile(sp, 25),
                "p75":    percentile(sp, 75),
                "p90":    percentile(sp, 90),
                "prices": sp,
            }
        if type_stats:
            stats[suburb] = {"state": "NSW", "types": type_stats, "total": total}

    print(f"  NSW suburbs with {min_sales}+ sales: {len(stats):,}")
    return stats


# ── VIC stats ────────────────────────────────────────────────────────────────────

def load_vic_stats(min_sales=10):
    if not os.path.exists(VIC_JSON):
        print(f"Warning: {VIC_JSON} not found — no VIC pages will be generated")
        return {}
    with open(VIC_JSON) as f:
        data = json.load(f)
    suburbs = data.get("suburbs", {})
    stats = {}
    for suburb, info in suburbs.items():
        if info.get("state") != "VIC":
            continue
        types = {}
        for ptype, td in (info.get("types") or {}).items():
            ann = td.get("annualSales", 0)
            med = td.get("median", 0)
            if ann >= 3 and med > 0:
                types[ptype] = {"count": ann, "median": med}
        if not types:
            continue
        total = sum(t["count"] for t in types.values())
        if total < min_sales:
            continue
        stats[suburb] = {"state": "VIC", "types": types, "total": total}
    print(f"  VIC suburbs with {min_sales}+ annual sales: {len(stats):,}")
    return stats


# ── HTML building blocks ──────────────────────────────────────────────────────────

NAV_SVG = """<svg width="20" height="20" viewBox="0 0 26 26" fill="none" aria-hidden="true">
  <circle cx="13" cy="13" r="11.5" stroke="#18181b" stroke-width="1.5"/>
  <circle cx="13" cy="13" r="6.5" stroke="#18181b" stroke-width="1.5"/>
  <circle cx="13" cy="13" r="2.5" fill="#18181b"/>
</svg>"""

SITE_HEADER = f"""<header class="site-header">
  <a class="brand" href="/">
    {NAV_SVG}
    <span class="brand-name">GetReal</span>
  </a>
</header>"""


def make_budget_rows_nsw(type_stats, primary_type):
    ts = type_stats.get(primary_type, {})
    median = ts.get("median", 0)
    prices = ts.get("prices", [])
    total  = ts.get("count", 0)
    if not prices or not median:
        return ""
    rows = ""
    for ratio in BUDGET_RATIOS:
        budget = round_budget(median * ratio)
        pct    = budget_access(prices, budget)
        est    = round(pct / 100 * total)
        letter, label, color, bg = get_grade(pct)
        rows += f"""
      <tr>
        <td><strong>{fmt_price_full(budget)}</strong></td>
        <td>{pct}%</td>
        <td><span class="grade-chip" style="background:{bg};color:{color};">{letter} — {label}</span></td>
        <td>~{est:,} of {total:,}</td>
      </tr>"""
    return rows


def make_budget_rows_vic(type_stats, primary_type):
    ts = type_stats.get(primary_type, {})
    median = ts.get("median", 0)
    total  = ts.get("count", 0)
    if not median:
        return ""
    rows = ""
    for ratio in BUDGET_RATIOS:
        budget = round_budget(median * ratio)
        pct    = vic_budget_access(median, budget)
        est    = round(pct / 100 * total)
        letter, label, color, bg = get_grade(pct)
        rows += f"""
      <tr>
        <td><strong>{fmt_price_full(budget)}</strong></td>
        <td>~{pct}%</td>
        <td><span class="grade-chip" style="background:{bg};color:{color};">{letter} — {label}</span></td>
        <td>~{est:,} of {total:,}</td>
      </tr>"""
    return rows


def make_dist_bars_nsw(prices, median):
    brackets = compute_brackets(median)
    total = len(prices)
    if not total:
        return ""
    bars = ""
    for lo, hi, label in brackets:
        count = sum(1 for p in prices if lo <= p < hi)
        pct   = round(100 * count / total)
        width = max(2, pct)
        bars += f"""
    <div class="dist-row">
      <span class="dist-label">{label}</span>
      <div class="dist-track"><div class="dist-bar" style="width:{width}%"></div></div>
      <span class="dist-pct">{pct}%</span>
    </div>"""
    return bars


def make_dist_bars_vic(median):
    brackets = compute_brackets(median)
    sigma = 0.4
    bars = ""
    for lo, hi, label in brackets:
        lo_z = (math.log(max(lo, 1)) - math.log(median)) / sigma if lo > 0 else -4
        hi_z = (math.log(hi) - math.log(median)) / sigma if hi < float('inf') else 4
        phi_lo = 0.5 * (1 + math.erf(lo_z / math.sqrt(2)))
        phi_hi = 0.5 * (1 + math.erf(hi_z / math.sqrt(2)))
        pct   = round(100 * (phi_hi - phi_lo))
        width = max(2, pct)
        bars += f"""
    <div class="dist-row">
      <span class="dist-label">{label}</span>
      <div class="dist-track"><div class="dist-bar" style="width:{width}%"></div></div>
      <span class="dist-pct">~{pct}%</span>
    </div>"""
    return bars


def make_lead_text(suburb_display, state, primary_type, total, median, data_label):
    depth  = "active" if total >= 30 else "thin"
    an     = "an" if depth[0] in "aeiou" else "a"
    period = "two-year" if state == "NSW" else "annual"
    access_budget = round_budget(median * 0.82)
    access_pct    = 50 if state == "VIC" else None  # approximation for lead text

    s = (f"{suburb_display} is {an} {depth} {primary_type} market "
         f"with {total:,} recorded sales in the {period} dataset. "
         f"The median {primary_type} price was {fmt_price(median)}.")
    if state == "NSW":
        s += (f" A buyer with a {fmt_price(access_budget)} budget "
              f"can access approximately {budget_access([], access_budget) or 'around 18'}% "
              f"of this market — use the search tool below for a precise figure.")
    return s


def make_faq(suburb_display, state, primary_type, median, total, p10, p90, data_year):
    type_label   = primary_type + "s"
    depth_label  = "active" if total >= 30 else "thin"
    depth_note   = " This classifies it as an active market (30+ sales per year)." if total >= 30 else ""

    budget_q = round_budget(median * 0.82)
    if state == "NSW":
        access_q = 18  # rough; real answer is in the table
        access_note = f"A {fmt_price_full(budget_q)} budget gives access to approximately {access_q}% of the {suburb_display} {primary_type} market — a limited but not impossible position. You would be competing for properties at the lower end of the market."
    else:
        access_q = vic_budget_access(median, budget_q)
        access_note = f"A {fmt_price_full(budget_q)} budget gives access to an estimated {access_q}% of the {suburb_display} {primary_type} market (estimated from market distribution curves)."

    price_note = (f"The median {primary_type} price in {suburb_display} was {fmt_price_full(median)} "
                  f"in {data_year}, based on {total:,} recorded sales from the "
                  f"{'NSW Valuer General' if state == 'NSW' else 'Victorian Valuer General'}.")

    sales_note = (f"{total:,} {type_label} were recorded in {suburb_display} in {data_year} "
                  f"by the {'NSW Valuer General' if state == 'NSW' else 'Victorian Valuer General'}."
                  f"{depth_note}")

    range_note = (f"Sale prices in {suburb_display} ranged from {fmt_price_full(p10)} (10th percentile) "
                  f"to {fmt_price_full(p90)} (90th percentile) in {data_year}.")

    return f"""
  <div class="faq-item">
    <h3>What is the median {primary_type} price in {suburb_display}?</h3>
    <p>{price_note}</p>
  </div>
  <div class="faq-item">
    <h3>Is {suburb_display} affordable on a {fmt_price_full(budget_q)} budget?</h3>
    <p>{access_note}</p>
  </div>
  <div class="faq-item">
    <h3>How many {type_label} sold in {suburb_display} in {data_year}?</h3>
    <p>{sales_note}</p>
  </div>
  <div class="faq-item">
    <h3>What is the price range for {primary_type}s in {suburb_display}?</h3>
    <p>{range_note}</p>
  </div>"""


def page_styles():
    return """<style>
  body { font-family: 'Inter', -apple-system, sans-serif; margin: 0; background: #0a0a0a; color: #f0f0f0; }
  .suburb-hero { background: #0a0a0a; padding: 2rem 1.5rem 1.5rem; max-width: 900px; margin: 0 auto; }
  .breadcrumb { font-family: monospace; font-size: 0.7rem; color: #555; margin-bottom: 1rem; }
  .breadcrumb a { color: #555; text-decoration: none; }
  .breadcrumb a:hover { color: #999; }
  .suburb-hero h1 { font-size: 2.4rem; font-weight: 800; margin: 0 0 0.5rem; letter-spacing: -0.02em; }
  .suburb-meta { font-family: monospace; font-size: 0.72rem; color: #555; text-transform: uppercase; letter-spacing: 0.06em; margin: 0; }
  .lead-block { background: #111; border-left: 4px solid #4caf50; padding: 1.5rem 1.5rem 1.5rem 1.25rem; font-size: 1.05rem; line-height: 1.75; color: #d0d0d0; max-width: 900px; margin: 0 auto; }
  .suburb-body { background: #ffffff; color: #18181b; padding: 0 1.5rem 3rem; }
  .suburb-section { max-width: 860px; margin: 0 auto 2.5rem; }
  .section-label { font-family: monospace; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.1em; color: #888; border-bottom: 1px solid #e0e0e0; padding-bottom: 0.5rem; margin-bottom: 1.25rem; }
  /* ── Tab switcher ── */
  .type-tabs { max-width: 860px; margin: 0 auto; display: flex; gap: 0; border-bottom: 2px solid #e0e0e0; padding-top: 1.75rem; }
  .tab-btn { font-family: monospace; font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.06em; background: none; border: none; border-bottom: 2px solid transparent; margin-bottom: -2px; padding: 0.6rem 1.1rem; cursor: pointer; color: #888; transition: color 0.1s; }
  .tab-btn:hover { color: #18181b; }
  .tab-btn.active { color: #18181b; border-bottom-color: #4caf50; font-weight: 600; }
  .tab-count { font-size: 0.65rem; color: #aaa; margin-left: 0.3rem; }
  .tab-btn.active .tab-count { color: #888; }
  .type-panel { padding-top: 2rem; }
  /* ── Stat cards ── */
  .stat-cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1px; background: #e0e0e0; border: 1px solid #e0e0e0; margin-bottom: 2.5rem; }
  .stat-card { background: #fff; padding: 1.25rem; }
  .stat-label { font-family: monospace; font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.08em; color: #888; margin-bottom: 0.4rem; }
  .stat-value { font-size: 1.6rem; font-weight: 700; color: #18181b; line-height: 1.1; }
  .stat-sub { font-family: monospace; font-size: 0.65rem; color: #aaa; margin-top: 0.3rem; }
  /* ── Budget table ── */
  .access-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  .access-table th { font-family: monospace; font-size: 0.65rem; text-transform: uppercase; letter-spacing: 0.06em; color: #888; text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #e0e0e0; }
  .access-table td { padding: 0.75rem; border-bottom: 1px solid #f0f0f0; vertical-align: middle; }
  .access-table tr:last-child td { border-bottom: none; }
  .grade-chip { display: inline-block; font-family: monospace; font-size: 0.72rem; font-weight: 600; padding: 0.25rem 0.6rem; border-radius: 3px; white-space: nowrap; }
  /* ── Distribution bars ── */
  .dist-row { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.6rem; }
  .dist-label { font-size: 0.82rem; color: #444; width: 130px; flex-shrink: 0; }
  .dist-track { flex: 1; background: #f0f0f0; height: 8px; border-radius: 4px; overflow: hidden; }
  .dist-bar { background: #4caf50; height: 100%; border-radius: 4px; }
  .dist-pct { font-family: monospace; font-size: 0.78rem; color: #666; width: 40px; text-align: right; flex-shrink: 0; }
  /* ── CTA + FAQ ── */
  .suburb-cta { max-width: 860px; margin: 0 auto 2.5rem; border: 2px solid #4caf50; padding: 1.75rem; text-align: center; }
  .suburb-cta p { font-size: 1.05rem; color: #18181b; margin: 0 0 1rem; }
  .suburb-cta a { display: inline-block; background: #4caf50; color: #fff; font-family: monospace; font-size: 0.75rem; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; padding: 0.75rem 1.5rem; text-decoration: none; }
  .suburb-cta a:hover { background: #388e3c; }
  .faq-item { margin-bottom: 1.5rem; }
  .faq-item h3 { font-size: 1rem; font-weight: 600; margin: 0 0 0.4rem; color: #18181b; }
  .faq-item p { color: #444; line-height: 1.65; margin: 0; font-size: 0.9rem; }
  .vic-note { font-family: monospace; font-size: 0.68rem; color: #888; background: #f9f9f9; border: 1px solid #e0e0e0; padding: 0.6rem 0.9rem; margin-bottom: 1.5rem; line-height: 1.6; }
  .page-footer { background: #0a0a0a; border-top: 1px solid #161616; padding: 2rem 1.5rem; font-family: monospace; font-size: 0.65rem; color: #333; line-height: 1.9; }
  .page-footer a { color: #333; text-decoration: underline; }
  @media (max-width: 600px) {
    .suburb-hero h1 { font-size: 1.6rem; }
    .stat-cards { grid-template-columns: 1fr; }
    .dist-label { width: 90px; font-size: 0.72rem; }
    .access-table td:last-child { display: none; }
    .access-table th:last-child { display: none; }
    .tab-btn { padding: 0.5rem 0.7rem; font-size: 0.65rem; }
  }
</style>"""


def make_type_panel(suburb_display, state, ptype, ts, data_year, vic_note):
    """Generate the stat cards + budget table + distribution for one property type."""
    median = ts.get("median", 0)
    count  = ts.get("count", 0)
    p10    = ts.get("p10", median)
    p90    = ts.get("p90", median)
    depth  = "Active market" if count >= 30 else "Thin market"
    period = "2 years" if state == "NSW" else "Annual · VGV 2025"

    if state == "NSW":
        budget_rows = make_budget_rows_nsw({ptype: ts}, ptype)
        dist_bars   = make_dist_bars_nsw(ts.get("prices", []), median)
        dist_note   = ""
    else:
        budget_rows = make_budget_rows_vic({ptype: ts}, ptype)
        dist_bars   = make_dist_bars_vic(median)
        dist_note   = vic_note

    return f"""
    <div class="stat-cards">
      <div class="stat-card">
        <div class="stat-label">Median price</div>
        <div class="stat-value">{fmt_price(median)}</div>
        <div class="stat-sub">{title_case(ptype)}s · {period}</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Sales ({data_year})</div>
        <div class="stat-value">{count:,}</div>
        <div class="stat-sub">{depth}</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Price range</div>
        <div class="stat-value">{fmt_price(p10)}–{fmt_price(p90)}</div>
        <div class="stat-sub">10th–90th pct</div>
      </div>
    </div>

    <div class="suburb-section" style="margin-bottom:1.5rem;">
      <div class="section-label">What different budgets can access</div>
      {dist_note}
      <table class="access-table">
        <thead>
          <tr>
            <th>Budget</th><th>Market access</th><th>Grade</th><th>Est. properties</th>
          </tr>
        </thead>
        <tbody>{budget_rows}</tbody>
      </table>
    </div>

    <div class="suburb-section">
      <div class="section-label">Price distribution</div>
      {dist_note}
      {dist_bars}
    </div>"""


def generate_suburb_page(suburb, state, type_stats, total_sales):
    """Generate full HTML for one suburb page with property-type tab switcher."""
    suburb_display = title_case(suburb)
    slug           = slugify(suburb)
    state_lower    = state.lower()

    # Sort types by sales count descending; primary = most sales
    ordered_types  = sorted(type_stats.keys(), key=lambda t: type_stats[t]["count"], reverse=True)
    primary_type   = ordered_types[0]
    ts_primary     = type_stats[primary_type]
    median         = ts_primary.get("median", 0)
    count          = ts_primary.get("count", 0)
    p10            = ts_primary.get("p10", median)
    p90            = ts_primary.get("p90", median)

    data_year = "the past 2 years" if state == "NSW" else "2025"
    data_src  = "NSW Valuer General" if state == "NSW" else "Victorian Valuer General"

    vic_note = ("""<div class="vic-note">Budget access and price distribution are <em>estimated</em> """
                """from NSW market distribution curves — individual sale records are not publicly """
                """available in Victoria. <a href="/methodology#vic-methodology">See methodology</a>.</div>"""
                if state == "VIC" else "")

    # ── Lead text (mentions all types) ─────────────────────────────────────
    type_summaries = []
    for pt in ordered_types:
        ts = type_stats[pt]
        type_summaries.append(
            f"{title_case(pt)}s at a median of {fmt_price_full(ts['median'])} "
            f"({ts['count']:,} sales)"
        )
    if len(type_summaries) > 1:
        type_str = "; ".join(type_summaries[:-1]) + f"; and {type_summaries[-1]}"
    else:
        type_str = type_summaries[0]

    total_all = sum(type_stats[t]["count"] for t in ordered_types)
    lead = (f"{suburb_display} recorded {total_all:,} residential sales in {data_year}, "
            f"comprising {type_str}. "
            f"The median {primary_type} price was {fmt_price_full(median)}.")
    if p10 and p90 and p10 != p90 and state == "NSW":
        lead += f" {title_case(primary_type)} prices ranged from {fmt_price(p10)} to {fmt_price(p90)}."

    # ── Tab buttons ─────────────────────────────────────────────────────────
    tab_btns = ""
    for i, pt in enumerate(ordered_types):
        active = "active" if i == 0 else ""
        c = type_stats[pt]["count"]
        tab_btns += (f'<button class="tab-btn {active}" data-type="{pt}" '
                     f'aria-selected="{"true" if i==0 else "false"}">'
                     f'{title_case(pt)}s <span class="tab-count">{c:,}</span></button>')

    # ── Type panels ─────────────────────────────────────────────────────────
    panels_html = ""
    for i, pt in enumerate(ordered_types):
        ts     = type_stats[pt]
        hidden = "" if i == 0 else " hidden"
        inner  = make_type_panel(suburb_display, state, pt, ts, data_year, vic_note)
        panels_html += f'\n  <div class="type-panel" data-type="{pt}"{hidden}>{inner}\n  </div>'

    # ── FAQ (primary type only for schema + page content) ───────────────────
    faq_html = make_faq(suburb_display, state, primary_type, median, count, p10, p90, data_year)

    # ── Schema ──────────────────────────────────────────────────────────────
    faq_schema = []
    for pt in ordered_types:
        ts  = type_stats[pt]
        med = ts.get("median", 0)
        cnt = ts.get("count", 0)
        faq_schema.append({
            "@type": "Question",
            "name": f"What is the median {pt} price in {suburb_display}?",
            "acceptedAnswer": {"@type": "Answer",
                               "text": (f"The median {pt} price in {suburb_display} was "
                                        f"{fmt_price_full(med)} in {data_year}, based on "
                                        f"{cnt:,} recorded sales from the {data_src}.")}
        })
    faq_schema.append({
        "@type": "Question",
        "name": f"How many properties sold in {suburb_display}?",
        "acceptedAnswer": {"@type": "Answer",
                           "text": (f"{total_all:,} residential properties were recorded in "
                                    f"{suburb_display} in {data_year} by the {data_src}.")}
    })

    schema = json.dumps({
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "FAQPage", "mainEntity": faq_schema},
            {"@type": "Dataset",
             "name": f"{suburb_display}, {state} property sales",
             "description": (f"Median prices and sales volumes for {suburb_display}, {state} — {data_year}."),
             "url": f"{BASE_URL}/suburbs/{state_lower}/{slug}",
             "spatialCoverage": {"@type": "Place", "name": suburb_display,
                                 "address": {"@type": "PostalAddress",
                                             "addressRegion": state, "addressCountry": "AU"}},
             "publisher": {"@type": "Organization", "name": "GetReal", "url": BASE_URL}},
        ]
    }, indent=2)

    canonical = f"{BASE_URL}/suburbs/{state_lower}/{slug}"
    type_list = " · ".join(f"{title_case(t)}s {fmt_price(type_stats[t]['median'])}" for t in ordered_types)
    meta_desc = (f"{suburb_display}, {state} property market: {type_list}. "
                 f"{total_all:,} sales in {data_year}. See price distributions and budget access scores.")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{suburb_display}, {state} property prices — GetReal</title>
  <meta name="description" content="{meta_desc}">
  <link rel="canonical" href="{canonical}">
  <meta property="og:title" content="{suburb_display}, {state} property prices — GetReal">
  <meta property="og:description" content="{meta_desc}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:type" content="article">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../../styles.css">
  <script type="application/ld+json">
{schema}
  </script>
  {page_styles()}
</head>
<body>

<a class="skip-link" href="#main">Skip to content</a>

{SITE_HEADER}

<section class="suburb-hero">
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <a href="/">Home</a> › <a href="/suburbs/{state_lower}/">{state} suburbs</a> › {suburb_display}
  </nav>
  <h1>{suburb_display}, {state}</h1>
  <p class="suburb-meta">{total_all:,} sales · {data_year} · {data_src}</p>
</section>

<div class="lead-block">{lead}</div>

<main id="main" class="suburb-body">

  <div class="type-tabs" role="tablist" aria-label="Property type">
    {tab_btns}
  </div>

  <div class="suburb-section">
    {panels_html}
  </div>

  <div class="suburb-cta">
    <p>See if your budget is realistic for {suburb_display}</p>
    <a href="/search?suburb={suburb_display}&state={state}">Check my search →</a>
  </div>

  <section class="suburb-section">
    <div class="section-label">Frequently asked questions</div>
    {faq_html}
  </section>

</main>

<footer class="page-footer">
  <p>Data: {data_src} {'individual sale records' if state == 'NSW' else 'quarterly property sales statistics'}. Updated {'weekly' if state == 'NSW' else 'quarterly'}. Prices are contract date, not settlement date.</p>
  <p>GetReal is a data tool, not financial advice. <a href="/methodology">Methodology</a> · <a href="/faq">FAQ</a> · <a href="/">Home</a></p>
  <p>© GetReal {date.today().year}</p>
</footer>

<script>
(function() {{
  var btns   = document.querySelectorAll('.tab-btn');
  var panels = document.querySelectorAll('.type-panel');
  btns.forEach(function(btn) {{
    btn.addEventListener('click', function() {{
      btns.forEach(function(b) {{ b.classList.remove('active'); b.setAttribute('aria-selected','false'); }});
      panels.forEach(function(p) {{ p.hidden = true; }});
      btn.classList.add('active');
      btn.setAttribute('aria-selected', 'true');
      var target = document.querySelector('.type-panel[data-type="' + btn.dataset.type + '"]');
      if (target) target.hidden = false;
    }});
  }});
}})();
</script>

</body>
</html>"""


# ── Index pages ──────────────────────────────────────────────────────────────────

def generate_state_index(state, suburbs_dict):
    state_lower = state.lower()
    rows = ""
    for suburb in sorted(suburbs_dict.keys()):
        info    = suburbs_dict[suburb]
        ts      = info["types"]
        primary = max(ts, key=lambda t: ts[t]["count"])
        median  = ts[primary].get("median", 0)
        count   = info["total"]
        slug    = slugify(suburb)
        rows += f"""
    <a class="suburb-row" href="/suburbs/{state_lower}/{slug}">
      <span class="suburb-name">{title_case(suburb)}</span>
      <span class="suburb-median">{fmt_price(median)}</span>
      <span class="suburb-count">{count:,} sales</span>
      <span class="suburb-arrow">›</span>
    </a>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{state} suburb property data — GetReal</title>
  <meta name="description" content="Median property prices and sales volumes for {state} suburbs, from official Valuer General data.">
  <link rel="canonical" href="{BASE_URL}/suburbs/{state_lower}/">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../styles.css">
  <style>
    .idx {{ max-width: 860px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; color: #f0f0f0; }}
    .idx h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
    .idx p {{ color: #999; font-size: 0.9rem; margin-bottom: 2rem; }}
    .suburb-list {{ display: grid; gap: 1px; background: #2a2a2a; border: 1px solid #2a2a2a; margin-top: 1rem; }}
    .suburb-row {{ background: #111; display: flex; align-items: center; gap: 1rem; padding: 0.85rem 1rem; text-decoration: none; color: #f0f0f0; transition: background 0.1s; }}
    .suburb-row:hover {{ background: #1a1a1a; }}
    .suburb-name {{ flex: 1; font-size: 0.9rem; font-weight: 500; }}
    .suburb-median {{ font-family: monospace; font-size: 0.8rem; color: #4caf50; width: 80px; text-align: right; }}
    .suburb-count {{ font-family: monospace; font-size: 0.72rem; color: #555; width: 80px; text-align: right; }}
    .suburb-arrow {{ color: #333; }}
  </style>
</head>
<body>
{SITE_HEADER}
<div class="idx">
  <h1>{state} property data by suburb</h1>
  <p>{len(suburbs_dict):,} suburbs · Real transaction data from the {state} Valuer General</p>
  <div class="suburb-list">{rows}
  </div>
</div>
</body>
</html>"""


def generate_combined_index(nsw_count, vic_count):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Australian suburb property data — GetReal</title>
  <meta name="description" content="Median property prices and sales volumes for {nsw_count + vic_count:,} Australian suburbs, from official Valuer General data.">
  <link rel="canonical" href="{BASE_URL}/suburbs/">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../styles.css">
  <style>
    .idx {{ max-width: 860px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; color: #f0f0f0; }}
    .idx h1 {{ font-size: 1.9rem; margin-bottom: 0.5rem; }}
    .idx p {{ color: #999; font-size: 0.9rem; margin-bottom: 2.5rem; max-width: 600px; line-height: 1.7; }}
    .state-cards {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1px; background: #2a2a2a; border: 1px solid #2a2a2a; }}
    .state-card {{ background: #111; padding: 2rem 1.5rem; text-decoration: none; color: #f0f0f0; display: block; }}
    .state-card:hover {{ background: #1a1a1a; }}
    .state-tag {{ font-family: monospace; font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.1em; color: #4caf50; margin-bottom: 0.5rem; }}
    .state-name {{ font-size: 1.4rem; font-weight: 700; margin-bottom: 0.3rem; }}
    .state-count {{ font-family: monospace; font-size: 0.72rem; color: #555; }}
  </style>
</head>
<body>
{SITE_HEADER}
<div class="idx">
  <h1>Australian suburb property data</h1>
  <p>Median prices, sales volumes, and price distributions for {nsw_count + vic_count:,} suburbs across NSW and Victoria — sourced directly from state Valuer General records.</p>
  <div class="state-cards">
    <a class="state-card" href="/suburbs/nsw/">
      <div class="state-tag">Individual sale records</div>
      <div class="state-name">New South Wales</div>
      <div class="state-count">{nsw_count:,} suburbs</div>
    </a>
    <a class="state-card" href="/suburbs/vic/">
      <div class="state-tag">VGV quarterly data</div>
      <div class="state-name">Victoria</div>
      <div class="state-count">{vic_count:,} suburbs</div>
    </a>
  </div>
</div>
</body>
</html>"""


# ── Sitemap ──────────────────────────────────────────────────────────────────────

def write_sitemap(nsw_slugs, vic_slugs):
    urls = []
    for slug in nsw_slugs:
        urls.append(f"  <url><loc>{BASE_URL}/suburbs/nsw/{slug}</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>0.6</priority></url>")
    for slug in vic_slugs:
        urls.append(f"  <url><loc>{BASE_URL}/suburbs/vic/{slug}</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>0.6</priority></url>")
    urls.append(f"  <url><loc>{BASE_URL}/suburbs/</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>")
    urls.append(f"  <url><loc>{BASE_URL}/suburbs/nsw/</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>")
    urls.append(f"  <url><loc>{BASE_URL}/suburbs/vic/</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>")

    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    xml += "\n".join(urls)
    xml += "\n</urlset>"
    with open("sitemap-suburbs.xml", "w") as f:
        f.write(xml)
    print(f"  sitemap-suburbs.xml written ({len(nsw_slugs) + len(vic_slugs):,} suburb URLs)")


# ── Main ─────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-fetch",  action="store_true", help="Use cached NSW data")
    parser.add_argument("--state",     choices=["nsw", "vic"], help="Only build one state")
    parser.add_argument("--min-sales", type=int, default=MIN_SALES)
    parser.add_argument("--limit",     type=int, default=0, help="Max pages per state (0=all)")
    parser.add_argument("--dry-run",   action="store_true", help="Stats only, no HTML written")
    args = parser.parse_args()

    # ── Load data ──────────────────────────────────────────────────────────────
    nsw_stats = {}
    vic_stats = {}

    if not args.state or args.state == "nsw":
        raw = load_or_fetch_nsw(no_fetch=args.no_fetch)
        nsw_stats = compute_nsw_stats(raw, min_sales=args.min_sales)

    if not args.state or args.state == "vic":
        vic_stats = load_vic_stats(min_sales=args.min_sales)

    total_pages = (len(nsw_stats) if not args.state or args.state == "nsw" else 0) + \
                  (len(vic_stats) if not args.state or args.state == "vic" else 0)
    print(f"\nTotal suburb pages to generate: {total_pages:,}")

    if args.dry_run:
        print("[DRY RUN] No files written.")
        return

    # ── Create output dirs ────────────────────────────────────────────────────
    (OUT_DIR / "nsw").mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "vic").mkdir(parents=True, exist_ok=True)

    # ── Generate NSW pages ────────────────────────────────────────────────────
    nsw_slugs = []
    if nsw_stats:
        suburbs = list(nsw_stats.items())
        if args.limit:
            suburbs = suburbs[:args.limit]
        print(f"\nGenerating {len(suburbs):,} NSW suburb pages...")
        for i, (suburb, info) in enumerate(suburbs):
            slug = slugify(suburb)
            html = generate_suburb_page(suburb, "NSW", info["types"], info["total"])
            path = OUT_DIR / "nsw" / f"{slug}.html"
            path.write_text(html, encoding="utf-8")
            nsw_slugs.append(slug)
            if (i + 1) % 500 == 0:
                print(f"  {i+1:,} NSW pages written...")
        print(f"  {len(nsw_slugs):,} NSW pages complete")

        idx = generate_state_index("NSW", nsw_stats if not args.limit else dict(list(nsw_stats.items())[:args.limit]))
        (OUT_DIR / "nsw" / "index.html").write_text(idx, encoding="utf-8")

    # ── Generate VIC pages ────────────────────────────────────────────────────
    vic_slugs = []
    if vic_stats:
        suburbs = list(vic_stats.items())
        if args.limit:
            suburbs = suburbs[:args.limit]
        print(f"\nGenerating {len(suburbs):,} VIC suburb pages...")
        for i, (suburb, info) in enumerate(suburbs):
            slug = slugify(suburb)
            html = generate_suburb_page(suburb, "VIC", info["types"], info["total"])
            path = OUT_DIR / "vic" / f"{slug}.html"
            path.write_text(html, encoding="utf-8")
            vic_slugs.append(slug)
            if (i + 1) % 500 == 0:
                print(f"  {i+1:,} VIC pages written...")
        print(f"  {len(vic_slugs):,} VIC pages complete")

        idx = generate_state_index("VIC", vic_stats if not args.limit else dict(list(vic_stats.items())[:args.limit]))
        (OUT_DIR / "vic" / "index.html").write_text(idx, encoding="utf-8")

    # ── Combined index ────────────────────────────────────────────────────────
    combined = generate_combined_index(len(nsw_slugs), len(vic_slugs))
    (OUT_DIR / "index.html").write_text(combined, encoding="utf-8")

    # ── Sitemap ───────────────────────────────────────────────────────────────
    print("\nWriting sitemap-suburbs.xml...")
    write_sitemap(nsw_slugs, vic_slugs)

    print(f"\n{'='*60}")
    print(f"DONE")
    print(f"{'='*60}")
    print(f"NSW pages:  {len(nsw_slugs):,}")
    print(f"VIC pages:  {len(vic_slugs):,}")
    print(f"Total:      {len(nsw_slugs) + len(vic_slugs):,}")
    print(f"\nDeploy: git add suburbs/ sitemap-suburbs.xml && git commit -m 'Add suburb pages' && git push")


if __name__ == "__main__":
    main()
